# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296f52a5f04ac23e0aa673ab2582b306c5d5c698ae8889748eeb4d50a31375b9ed06789cfaa055050f4ecf1fb70d2f48249de3eadced27de34f22d0f499ed00c

test:
  secret_key_base: 34bf8cdd04bc6b2dae824681bafc482a4f0dc5640ceac8997527e0b176fe1a203bbe040afc0228c0894b5f33d1121814bc9498de4c6c6a40b260be3b599103d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
